## Ingesting data from flat files (e.g., CSV, TSV, Excel, TXT, JSON, XML)

In [1]:
#import all the useful libraries
import pandas as pd
import requests
import xml.etree.ElementTree as ET
import json

In [3]:
# CSV
csv_url = '/content/boston_house_prices.csv'
df_csv = pd.read_csv(csv_url, skiprows=1)
print("First Few rows of the CSV Data:")
print(df_csv.head())

First Few rows of the CSV Data:
      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7

        B  LSTAT  MEDV
0  396.90   4.98  24.0
1  396.90   9.14  21.6
2  392.83   4.03  34.7
3  394.63   2.94  33.4
4  396.90   5.33  36.2

In [5]:
# Excel
excel_url = '/content/Employee Data.xlsx'
df_excel = pd.read_excel(excel_url)
print("Last Few rows of the Excel Data:")
print(df_excel.tail())

Last Few rows of the Excel Data:
       EEID       Job Title  Department        Business Unit  Gender  \
995  E03094     Sr. Analyst   Marketing  Speciality Products    Male
996  E01909         Analyst     Finance  Speciality Products  Female
997  E04398        Director   Marketing  Speciality Products    Male
998  E02521     Sr. Analyst     Finance  Speciality Products  Female
999  E03545  Vice President  Accounting            Corporate  Female

     Ethnicity  Age  Hire Date  Annual Salary  Bonus %        Country  \
995  Caucasian   33 2016-09-18          98427     0.00  United States
996      Asian   44 2010-05-31          47387     0.00          China
997      Asian   31 2019-06-10         176710     0.15  United States
998      Asian   33 2012-01-28          95960     0.00          China
999      Asian   63 2020-07-26         216195     0.31  United States

         City  Exit Date
995  Columbus        NaT
996   Chengdu 2018-01-08
997     Miami        NaT
998   Chengdu        NaT
999     Miami        NaT

In [6]:
# TXT
txt_url = 'https://www.gutenberg.org/files/1342/1342-0.txt'
response = requests.get(txt_url)
txt_data = response.text
print("First 200 characters of the TXT Data:")
print(txt_data[:200]) # Print first 200 characters

First 200 characters of the TXT Data:
*** START OF THE PROJECT GUTENBERG EBOOK 1342 ***




                            [Illustration:

                             GEORGE ALLEN
                               PUBLISHER

In [7]:
#JSON

# Opening JSON file
f = open('/content/sample_users_with_id.json')

# returns JSON object as
# a dictionary
data = json.load(f)

# Iterating through the json
given_names = [user["given_name"] for user in data if "given_name" in user]

# Print the names
print(given_names)

# Closing file
f.close()

['Hello', 'Hello1', 'John', 'Jane', 'Dummy']

## Ingesting data from a database

In [8]:
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

# read csv files
df_BP = pd.read_csv('/content/BUSINESS-PROCESS.csv')
df_TD = pd.read_csv('/content/timedim.csv')
df_PR = pd.read_csv('/content/phonerate.csv')
df_LO = pd.read_csv('/content/location.csv')

In [9]:
# connect to database
conn = sqlite3.connect("DEdb")
cur = conn.cursor()

In [10]:
# load dataframes into database As tables with names BP,DT,PR, LO
df_BP.to_sql("BP", conn)
df_TD.to_sql("DT",conn)
df_PR.to_sql('PR',conn)
df_LO.to_sql('LO',conn)

1500

In [11]:
# CHECK IF DATA INSERTED INTO TABLES BP,DT,PR, LO
BP = pd.read_sql('SELECT * FROM BP', conn)
BP

,index,ID_time,ID_phoneRate,ID_location_Caller,ID_location_Receiver,Price,NumberOfCalls
0,0,3,1,877,757,15250,48
1,1,3,1,878,758,15250,48
2,2,3,1,879,759,15250,48
3,3,3,1,880,760,15250,48
4,4,3,1,881,761,15250,48
...,...,...,...,...,...,...,...
7803,7803,30,5,910,790,50400,72
7804,7804,30,5,911,791,50400,72
7805,7805,30,5,912,792,50400,72
7806,7806,30,5,913,793,50400,72
7807,7807,30,5,914,794,50400,72

In [12]:
TD=pd.read_sql('SELECT * FROM DT', conn)
TD

    index  ID_time        DayofWeek DateMonth  DateYear
0       0        1  tuesday            Jul-03      2003
1       1        2  wednesday          Jul-03      2003
2       2        3  thursday           Jul-03      2003
3       3        4  friday             Jul-03      2003
4       4        5  saturday           Jul-03      2003
5       5        6  friday             Aug-03      2003
6       6        7  saturday           Aug-03      2003
7       7        8  sunday             Aug-03      2003
8       8        9  monday             Aug-03      2003
9       9       10  tuesday            Aug-03      2003
10     10       11  wednesday          Oct-03      2003
11     11       12  thursday           Oct-03      2003
12     12       13  friday             Oct-03      2003
13     13       14  saturday           Oct-03      2003
14     14       15  sunday             Oct-03      2003
15     15       16  thursday           Jul-04      2004
16     16       17  friday             Jul-04      2004
17     17       18  saturday           Jul-04      2004
18     18       19  sunday             Jul-04      2004
19     19       20  monday             Jul-04      2004
20     20       21  sunday             Aug-04      2004
21     21       22  monday             Aug-04      2004
22     22       23  tuesday            Aug-04      2004
23     23       24  wednesday          Aug-04      2004
24     24       25  thursday           Aug-04      2004
25     25       26  friday             Oct-04      2004
26     26       27  saturday           Oct-04      2004
27     27       28  sunday             Oct-04      2004
28     28       29  monday             Oct-04      2004
29     29       30  tuesday            Oct-04      2004

## Ingest data from Application progam interface (API)

In [13]:
import requests
import json
#API Documentation: https://openweathermap.org/current

currentweather = requests.get('https://api.openweathermap.org/data/2.5/weather?q=London&appid=b29954cc60e659dc3ea53752ae96aba4')
print(currentweather.status_code)

print(currentweather.json())

# Save the JSON data to a file
with open('currentweather_data.json', 'w') as file:
    json.dump(data, file, indent=4)

200
{'coord': {'lon': -0.1257, 'lat': 51.5085}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 288.24, 'feels_like': 287.97, 'temp_min': 287.35, 'temp_max': 289.01, 'pressure': 1002, 'humidity': 83, 'sea_level': 1002, 'grnd_level': 998}, 'visibility': 10000, 'wind': {'speed': 9.77, 'deg': 250, 'gust': 15.43}, 'clouds': {'all': 100}, 'dt': 1727706102, 'sys': {'type': 2, 'id': 2075535, 'country': 'GB', 'sunrise': 1727675994, 'sunset': 1727718044}, 'timezone': 3600, 'id': 2643743, 'name': 'London', 'cod': 200}

In [14]:
import requests
import json
#API Documentation: https://openweathermap.org/forecast5

# Make a GET request to the API
ForecastData = requests.get('https://api.openweathermap.org/data/2.5/forecast?q=london&appid=b29954cc60e659dc3ea53752ae96aba4')
print(ForecastData.status_code)

print(ForecastData.json())

# Save the JSON data to a file
with open('ForecastData.json', 'w') as file:
    json.dump(data, file, indent=4)

200
{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1727708400, 'main': {'temp': 288.17, 'feels_like': 287.89, 'temp_min': 286.56, 'temp_max': 288.17, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 998, 'humidity': 83, 'temp_kf': 1.61}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 6.71, 'deg': 265, 'gust': 13.37}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.17}, 'sys': {'pod': 'd'}, 'dt_txt': '2024-09-30 15:00:00'}, {'dt': 1727719200, 'main': {'temp': 287.48, 'feels_like': 287.11, 'temp_min': 286.11, 'temp_max': 287.48, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 1000, 'humidity': 82, 'temp_kf': 1.37}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 99}, 'wind': {'speed': 7.04, 'deg': 270, 'gust': 13.64}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.12}, 'sys': {'pod': 'n'}, 'dt_txt': '2024-09-30 18:00:00'}, {'dt': 1727730000, 'main': {'temp': 286.55, 'feels_like': 286.06, 'temp_min': 285.74, 'temp_max': 286.55, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1002, 'humidity': 81, 'temp_kf': 0.81}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 7.47, 'deg': 271, 'gust': 13.55}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-09-30 21:00:00'}, {'dt': 1727740800, 'main': {'temp': 284.8, 'feels_like': 284.08, 'temp_min': 284.8, 'temp_max': 284.8, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1003, 'humidity': 79, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 97}, 'wind': {'speed': 6.55, 'deg': 271, 'gust': 13.13}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-01 00:00:00'}, {'dt': 1727751600, 'main': {'temp': 284.82, 'feels_like': 284.13, 'temp_min': 284.82, 'temp_max': 284.82, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 80, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.76, 'deg': 273, 'gust': 11.48}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-01 03:00:00'}, {'dt': 1727762400, 'main': {'temp': 284.94, 'feels_like': 284.37, 'temp_min': 284.94, 'temp_max': 284.94, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 84, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.63, 'deg': 276, 'gust': 11.53}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-01 06:00:00'}, {'dt': 1727773200, 'main': {'temp': 284.92, 'feels_like': 284.4, 'temp_min': 284.92, 'temp_max': 284.92, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1004, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.79, 'deg': 287, 'gust': 12.81}, 'visibility': 10000, 'pop': 0.87, 'rain': {'3h': 0.54}, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-01 09:00:00'}, {'dt': 1727784000, 'main': {'temp': 284.9, 'feels_like': 284.48, 'temp_min': 284.9, 'temp_max': 284.9, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1005, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 6.06, 'deg': 298, 'gust': 12.44}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 3.07}, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-01 12:00:00'}, {'dt': 1727794800, 'main': {'temp': 285.36, 'feels_like': 284.96, 'temp_min': 285.36, 'temp_max': 285.36, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1005, 'humidity': 89, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.03, 'deg': 315, 'gust': 10.89}, 'visibility': 10000, 'pop': 0.95, 'rain': {'3h': 0.63}, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-01 15:00:00'}, {'dt': 1727805600, 'main': {'temp': 285.47, 'feels_like': 285.08, 'temp_min': 285.47, 'temp_max': 285.47, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1006, 'humidity': 89, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.34, 'deg': 326, 'gust': 10.51}, 'visibility': 10000, 'pop': 0.5, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-01 18:00:00'}, {'dt': 1727816400, 'main': {'temp': 285.31, 'feels_like': 284.98, 'temp_min': 285.31, 'temp_max': 285.31, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 92, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.08, 'deg': 332, 'gust': 10.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-01 21:00:00'}, {'dt': 1727827200, 'main': {'temp': 285.41, 'feels_like': 285.09, 'temp_min': 285.41, 'temp_max': 285.41, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1007, 'humidity': 92, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.07, 'deg': 341, 'gust': 9.77}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.1}, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-02 00:00:00'}, {'dt': 1727838000, 'main': {'temp': 286.06, 'feels_like': 285.7, 'temp_min': 286.06, 'temp_max': 286.06, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1007, 'humidity': 88, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.16, 'deg': 5, 'gust': 9.06}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-02 03:00:00'}, {'dt': 1727848800, 'main': {'temp': 285.86, 'feels_like': 285.54, 'temp_min': 285.86, 'temp_max': 285.86, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.99, 'deg': 6, 'gust': 9.71}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-02 06:00:00'}, {'dt': 1727859600, 'main': {'temp': 287.56, 'feels_like': 287.15, 'temp_min': 287.56, 'temp_max': 287.56, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 80, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 58}, 'wind': {'speed': 4.63, 'deg': 23, 'gust': 8.71}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-02 09:00:00'}, {'dt': 1727870400, 'main': {'temp': 287.71, 'feels_like': 287.23, 'temp_min': 287.71, 'temp_max': 287.71, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 77, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 75}, 'wind': {'speed': 4.49, 'deg': 38, 'gust': 8.63}, 'visibility': 10000, 'pop': 0.25, 'rain': {'3h': 0.5}, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-02 12:00:00'}, {'dt': 1727881200, 'main': {'temp': 289.38, 'feels_like': 288.76, 'temp_min': 289.38, 'temp_max': 289.38, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 65, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 71}, 'wind': {'speed': 5.25, 'deg': 34, 'gust': 8.5}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 0.73}, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-02 15:00:00'}, {'dt': 1727892000, 'main': {'temp': 286.54, 'feels_like': 285.95, 'temp_min': 286.54, 'temp_max': 286.54, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1013, 'humidity': 77, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 45}, 'wind': {'speed': 5.27, 'deg': 30, 'gust': 10.23}, 'visibility': 10000, 'pop': 0.8, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-02 18:00:00'}, {'dt': 1727902800, 'main': {'temp': 286.3, 'feels_like': 285.71, 'temp_min': 286.3, 'temp_max': 286.3, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1014, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 83}, 'wind': {'speed': 5.13, 'deg': 42, 'gust': 10.62}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.12}, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-02 21:00:00'}, {'dt': 1727913600, 'main': {'temp': 286.36, 'feels_like': 285.36, 'temp_min': 286.36, 'temp_max': 286.36, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1015, 'humidity': 62, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 85}, 'wind': {'speed': 5.02, 'deg': 42, 'gust': 9.59}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-03 00:00:00'}, {'dt': 1727924400, 'main': {'temp': 286.51, 'feels_like': 285.34, 'temp_min': 286.51, 'temp_max': 286.51, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1016, 'humidity': 55, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 97}, 'wind': {'speed': 4.7, 'deg': 40, 'gust': 8.94}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-03 03:00:00'}, {'dt': 1727935200, 'main': {'temp': 284.76, 'feels_like': 283.83, 'temp_min': 284.76, 'temp_max': 284.76, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1017, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 93}, 'wind': {'speed': 3.44, 'deg': 35, 'gust': 9.01}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-03 06:00:00'}, {'dt': 1727946000, 'main': {'temp': 286.32, 'feels_like': 285.34, 'temp_min': 286.32, 'temp_max': 286.32, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1018, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.09, 'deg': 45, 'gust': 8.88}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-03 09:00:00'}, {'dt': 1727956800, 'main': {'temp': 289.11, 'feels_like': 288.09, 'temp_min': 289.11, 'temp_max': 289.11, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1018, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 94}, 'wind': {'speed': 4.44, 'deg': 57, 'gust': 6.59}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-03 12:00:00'}, {'dt': 1727967600, 'main': {'temp': 289.56, 'feels_like': 288.48, 'temp_min': 289.56, 'temp_max': 289.56, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1018, 'humidity': 47, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 60}, 'wind': {'speed': 4.17, 'deg': 72, 'gust': 5.94}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-03 15:00:00'}, {'dt': 1727978400, 'main': {'temp': 286.89, 'feels_like': 285.91, 'temp_min': 286.89, 'temp_max': 286.89, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1019, 'humidity': 61, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 34}, 'wind': {'speed': 2.48, 'deg': 90, 'gust': 6.33}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-03 18:00:00'}, {'dt': 1727989200, 'main': {'temp': 285.48, 'feels_like': 284.54, 'temp_min': 285.48, 'temp_max': 285.48, 'pressure': 1024, 'sea_level': 1024, 'grnd_level': 1019, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 2.18, 'deg': 57, 'gust': 7.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-03 21:00:00'}, {'dt': 1728000000, 'main': {'temp': 284.28, 'feels_like': 283.49, 'temp_min': 284.28, 'temp_max': 284.28, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1019, 'humidity': 78, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 1.46, 'deg': 43, 'gust': 3.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-04 00:00:00'}, {'dt': 1728010800, 'main': {'temp': 284.65, 'feels_like': 283.87, 'temp_min': 284.65, 'temp_max': 284.65, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1018, 'humidity': 77, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 66}, 'wind': {'speed': 0.96, 'deg': 22, 'gust': 1.81}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-04 03:00:00'}, {'dt': 1728021600, 'main': {'temp': 285.01, 'feels_like': 284.16, 'temp_min': 285.01, 'temp_max': 285.01, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1018, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 83}, 'wind': {'speed': 0.6, 'deg': 93, 'gust': 1.03}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-04 06:00:00'}, {'dt': 1728032400, 'main': {'temp': 286.99, 'feels_like': 286, 'temp_min': 286.99, 'temp_max': 286.99, 'pressure': 1023, 'sea_level': 1023, 'grnd_level': 1018, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.06, 'deg': 160, 'gust': 2.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-04 09:00:00'}, {'dt': 1728043200, 'main': {'temp': 289.05, 'feels_like': 288, 'temp_min': 289.05, 'temp_max': 289.05, 'pressure': 1022, 'sea_level': 1022, 'grnd_level': 1018, 'humidity': 50, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 92}, 'wind': {'speed': 2.32, 'deg': 157, 'gust': 2.89}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-04 12:00:00'}, {'dt': 1728054000, 'main': {'temp': 289.54, 'feels_like': 288.51, 'temp_min': 289.54, 'temp_max': 289.54, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1016, 'humidity': 49, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.26, 'deg': 176, 'gust': 2.54}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-04 15:00:00'}, {'dt': 1728064800, 'main': {'temp': 287.1, 'feels_like': 286.09, 'temp_min': 287.1, 'temp_max': 287.1, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1017, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.73, 'deg': 182, 'gust': 4.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-04 18:00:00'}, {'dt': 1728075600, 'main': {'temp': 284.97, 'feels_like': 283.88, 'temp_min': 284.97, 'temp_max': 284.97, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1017, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 67}, 'wind': {'speed': 1.99, 'deg': 159, 'gust': 5.31}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-04 21:00:00'}, {'dt': 1728086400, 'main': {'temp': 283.77, 'feels_like': 282.77, 'temp_min': 283.77, 'temp_max': 283.77, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1015, 'humidity': 72, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 43}, 'wind': {'speed': 1.7, 'deg': 148, 'gust': 6.07}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-05 00:00:00'}, {'dt': 1728097200, 'main': {'temp': 283.41, 'feels_like': 282.45, 'temp_min': 283.41, 'temp_max': 283.41, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1014, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 69}, 'wind': {'speed': 1.83, 'deg': 147, 'gust': 6.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-05 03:00:00'}, {'dt': 1728108000, 'main': {'temp': 283.38, 'feels_like': 282.42, 'temp_min': 283.38, 'temp_max': 283.38, 'pressure': 1017, 'sea_level': 1017, 'grnd_level': 1012, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 85}, 'wind': {'speed': 2.57, 'deg': 148, 'gust': 8.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2024-10-05 06:00:00'}, {'dt': 1728118800, 'main': {'temp': 286.46, 'feels_like': 285.62, 'temp_min': 286.46, 'temp_max': 286.46, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1012, 'humidity': 68, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.64, 'deg': 164, 'gust': 9.08}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-05 09:00:00'}, {'dt': 1728129600, 'main': {'temp': 287.16, 'feels_like': 286.34, 'temp_min': 287.16, 'temp_max': 287.16, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.34, 'deg': 174, 'gust': 8.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2024-10-05 12:00:00'}], 'city': {'id': 2643743, 'name': 'London', 'coord': {'lat': 51.5085, 'lon': -0.1257}, 'country': 'GB', 'population': 1000000, 'timezone': 3600, 'sunrise': 1727675994, 'sunset': 1727718044}}

## Move around your data Command Line

In [15]:
!pwd

/content

In [16]:
ls -la

total 844
drwxr-xr-x 1 root root   4096 Sep 30 14:34  ./
drwxr-xr-x 1 root root   4096 Sep 30 14:31  ../
-rw-r--r-- 1 root root  34742 Sep 30 14:32  boston_house_prices.csv
-rw-r--r-- 1 root root 179224 Sep 30 14:32  BUSINESS-PROCESS.csv
drwxr-xr-x 4 root root   4096 Sep 25 18:24  .config/
-rw-r--r-- 1 root root   2124 Sep 30 14:34  currentweather_data.json
-rw-r--r-- 1 root root 434176 Sep 30 14:34  DEdb
-rw-r--r-- 1 root root  86805 Sep 30 14:32 'Employee Data.xlsx'
-rw-r--r-- 1 root root   2124 Sep 30 14:34  ForecastData.json
-rw-r--r-- 1 root root  84820 Sep 30 14:32  location.csv
-rw-r--r-- 1 root root    112 Sep 30 14:32  phonerate.csv
drwxr-xr-x 1 root root   4096 Sep 25 18:24  sample_data/
-rw-r--r-- 1 root root   1884 Sep 30 14:32  sample_users_with_id.json
-rw-r--r-- 1 root root    989 Sep 30 14:32  timedim.csv

In [17]:
mkdir DE_Wk2

In [18]:
cd DE_Wk2

/content/DE_Wk2

In [20]:
cd ..

/content

In [21]:
mv *.json *.csv *.xlsx /content/DE_Wk2

In [22]:
!cd DE_Wk2

In [23]:
!ls -la

total 444
drwxr-xr-x 1 root root   4096 Sep 30 14:35 .
drwxr-xr-x 1 root root   4096 Sep 30 14:31 ..
drwxr-xr-x 4 root root   4096 Sep 25 18:24 .config
-rw-r--r-- 1 root root 434176 Sep 30 14:34 DEdb
drwxr-xr-x 2 root root   4096 Sep 30 14:35 DE_Wk2
drwxr-xr-x 1 root root   4096 Sep 25 18:24 sample_data